Updated rpm/specfiles/buildall script and rpm/README.md

diff --git a/rpm/specfiles/buildall b/rpm/specfiles/buildall
--- a/rpm/specfiles/buildall
+++ b/rpm/specfiles/buildall
@@ -11,8 +11,14 @@ for X in *.spec
 do
 	echo ================== $X
 	spectool -g -R $X
-	sudo yum-builddeps -y $X
-	rpmbuild -ba $X || (echo "$(basename $0): Build of $X failed" >&2 ; exit 1)
+	sudo dnf builddep -y $X
+	if rpmbuild -ba $X 
+	then
+		echo "$(basename $0): Build of $X completed"
+	else
+		echo "$(basename $0): Build of $X failed" >&2
+		exit 1
+	fi
 done
 echo
 echo "Output RPMS will be in $(rpm --eval "%{_topdir}/RPMS")"
