Completed download/setup/shutdown options, added all options to desktop file

diff --git a/demo/simengine-demo b/demo/simengine-demo
--- a/demo/simengine-demo
+++ b/demo/simengine-demo
@@ -11,7 +11,9 @@ YONponm+7gb78vRGV2CwAAAAGWNocmlzQHphbWJpYS5jZG90LnN5c3RlbXMBAgME
 -----END OPENSSH PRIVATE KEY-----"
 
 se_key_file="$HOME/.ssh/id_ed25519_simengine"
-simengine_login="root@10.10.10.100"
+simengine_login="root@192.168.122.100"
+
+IMG_DIR="/var/lib/libvirt/images"
 
 LOGFILE="$(mktemp)"
 ZENITY=""
@@ -72,7 +74,7 @@ demo(){
 
 open_dash(){
     xdg-open "http://localhost:8888" &> /dev/null
-    xdg-open "http://localhost:9090" &> /dev/null 
+    xdg-open "http://localhost:9090" &> /dev/null
 }
 
 remove_se_key(){
@@ -87,18 +89,46 @@ remove_se_key(){
 }
 
 se_download(){
-    echo "$(basename $0): Downloading simengine vm image..."
-    curl http://simengine-anvil-demo.cdot.systems/SIMENGINE-QCOW2 --output /var/lib/libvirt/images/SIMENGINE-QCOW2 && curl http://simengine-anvil-demo.cdot.systems/SE-XML --output /path/to/SE-XML
+    echo "$(basename $0): Downloading simengine vm image and xml..."
+    [ "$ZENITY" ] && zenity --info --text "Downloading simengine vm image and xml.\nPlease wait, this will take some time." --width 300 &
+    curl http://simengine-anvil-demo.cdot.systems/vm-images/simengine.img.xz -o "$IMG_DIR/simengine.img.xz" && xz -d "$IMG_DIR/simengine.img.xz"
+    curl http://simengine-anvil-demo.cdot.systems/vm-images/simengine.xml -o "$IMG_DIR/simengine.xml"
+    if [ $? -ne 0 ]
+    then
+        echo "$(basename $0): Failed to download simengine image and xml"
+        n0_exit 1
+    else
+        [ "$ZENITY" ] && zenity --info --text "Download comeplete!" --width 300 &
+        sleep 5
+    fi
 }
 
 se_setup(){
     echo "$(basename $0): Setting up simengine vm..."
-    virsh define /path/to/SE-XML
+    [ "$ZENITY" ] && zenity --info --text "Setting up simengine vm..." --width 300 &
+    virsh define "$IMG_DIR/simengine.xml"
+    if [ $? -ne 0 ]
+    then
+        echo "$(basename $0): Failed to define simengine vm..."
+        n0_exit 1
+    else
+        echo "$(basename $0): Setup complete!"
+        [ "$ZENITY" ] && zenity --info --text "Setup complete!" --width 300 &
+        sleep 5
+    fi
 }
 
 se_shutdown(){
     echo "$(basename $0): Shutting down simengine vm..."
     virsh shutdown simengine
+    if [ $? -ne 0 ]
+    then
+        echo "$(basename $0): Failed to shut down simengine vm..."
+        n0_exit 1
+    else
+        [ "$ZENITY" ] && zenity --info --text "Simengine successfully shut down." --width 300 &
+        sleep 5
+    fi
 }
 
 start_se(){
