Expanding error handling, adding safety in dir paths with macros, and removing the use of ssh-add

diff --git a/demo/simengine-demo b/demo/simengine-demo
--- a/demo/simengine-demo
+++ b/demo/simengine-demo
@@ -8,46 +8,44 @@ AAAEBEPxSok/tlvd8Zhd1f8stIZnCIJZ5UOZWNx26o7IHlmJYwLUQZt8KgHYCK/+RDzn1o
 YONponm+7gb78vRGV2CwAAAAGWNocmlzQHphbWJpYS5jZG90LnN5c3RlbXMBAgME
 -----END OPENSSH PRIVATE KEY-----"
 
-file=/home/$USER/.ssh/id_ed25519_simengine
-#to-do: modify this to account for additional simengine vms on a system
-simengine_login=root@10.10.10.100
+se_key_file="$HOME/.ssh/id_ed25519_simengine"
+simengine_login="root@10.10.10.100"
 
 create_se_key(){
 
-    if [[ ! -f "$file" ]]
+    if [[ ! -f "$se_key_file" ]]
     then
-        echo "Creating simengine ssh key..."
-        echo "$key" >> "$file"
-
-        if [[ $? -eq 0 ]]
+        echo "$(basename $0): Creating simengine ssh key..."
+        mkdir "$(dirname $se_key_file)" 2> /dev/null && chmod 0700 "$(dirname $se_key_file)"
+        
+        echo "$key" >> "$se_key_file" && chmod 600 "$se_key_file"
+        if [ $? -ne 0 ]
         then
-            echo "Simengine ssh key created"
-            chmod 600 "$file"
-            ssh-add "$file"
+            echo "$(basename $0): Failed to create simengine ssh key"
+            exit 1
         else
-            echo "Failed to create Simengine ssh key"
+            echo "$(basename $0): Simengine ssh key successfully created"
         fi
-    else
-        ssh-add "$file"
     fi
 }
 
 remove_se_key(){
 
-    echo "Removing simengine ssh key..."
-    ssh-add -d "$file"
-
-    if rm "$file"
+    echo "$(basename $0): Removing simengine ssh key..."
+    rm "$se_key_file" && echo "$(basename $0): Simengine ssh key removed"
+    if [ $? -ne 0 ]
     then
-        echo "Simengine key removed"
+        echo "$(basename $0): Failed to remove simengine ssh key"
+        exit 1
     fi
 }
 
 start_se(){
-    echo "Starting simengine..."
-    #to-do: modify this to account for multiple simengine vms on a system
-    virsh start simengine
-    ssh -n "$simengine_login" systemctl restart simengine-core
+    
+    echo "$(basename $0): Starting simengine..."
+    virsh start simengine && ssh -n ConnectTimeout=10 -i "$se_key_file" "$simengine_login" systemctl restart simengine-core
+    #not exiting on errors here because se could just already be running
+    #only restarting se-core if simengine was not open already
 }
 
 open_dash(){
@@ -60,9 +58,9 @@ connect(){
     declare -i count=0
     declare -i rt=0
 
-    echo "Waiting for inner vms..."
+    echo "$(basename $0): Waiting for inner vms..."
     
-    until  $(ssh -n -o ConnectTimeout=8 "$simengine_login" "su -l -c 'get-system-status'")
+    until  $(ssh -n -o ConnectTimeout=10 -i "$se_key_file" "$simengine_login" "su -l -c 'get-system-status'")
     do
         if [[ $count -eq 2 ]]
         then
@@ -76,11 +74,12 @@ connect(){
 
     if [[ rt -eq 0 ]]   
     then
-        echo "Success!"
+        echo "$(basename $0): Success!"
         ( sleep 5; open_dash ) &
-        ssh "$simengine_login" -L8888:localhost:80 -L8000:localhost:8000 -L9090:10.201.4.1:80 -L8000:10.201.4.1:8000
+        ssh -i "$se_key_file" "$simengine_login" -L8888:localhost:80 -L8000:localhost:8000 -L9090:10.201.4.1:80 -L8000:10.201.4.1:8000
     else
-        echo "Simengine inner vms unreachable"
+        echo "$(basename $0): Simengine inner vms unreachable"
+        exit 3
     fi
 }
 
